name = "openai-api-wrapper"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# [vars]
# MY_VARIABLE = "production_value"

[vars]
REAL_OPENAI_KEY = "YOUR_REAL_OPENAI_KEY"
DUMMY_WRAPPER_KEY = "YOUR_DUMMY_WRAPPER_KEY"
AI_GATEWAY_ENDPOINT_URL = "https://api.openai.com"
